server:
  port: 6023
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/medical_report?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: MYSQL

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志（可选）
#logging:
#  level:
#    root: DEBUG  # 开启DEBUG级别日志
  global-config:
    db-config:
      id-type: auto  # 主键自增（与数据库`AUTO_INCREMENT`对应）
  type-aliases-package: com.example.medicalreportstructurizer.entity
deepseek:
  api:
    base-url: https://api.deepseek.com/v1/chat/completions
    api-key:  
    timeout: 10000  # 请求超时时间（ms）
